### ISSUE TITLE
Support user provide IP for NATGateay

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#56] opened 2020-03-30 06:56 UTC
**What would you like to be added**:
When user create an shoot, we allow user to provide EIP for NATGateway source entries. EIP should be configured by zone, because EIP can only attached to VSwitch level.

```
apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  vpc: # specify either 'id' or 'cidr'
  # id: my-vpc
    cidr: 10.250.0.0/16
  zones:
  - name: eu-central-1a
    workers: 10.250.1.0/24
    eips: ["1.2.3.4"]
```
**Why is this needed**:

**Comment by rfranzke** [comment] 2020-03-30 07:44
Duplicate of #55?

**Closed** 2020-03-30 07:46 UTC
Labels: kind/enhancement
